# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1="[\$?] [\A] [\u@\h \W]\n\$ "

# Check the window size after each command and, if necessary,
# Update the values of LINES and COLUMNS.
shopt -s checkwinsize

# bash history configurations
HISTSIZE=99999
HISTFILESIZE=-1
HISTCONTROL=ignoredups

export EDITOR=nvim

# enable fzf keybindings, https://github.com/junegunn/fzf
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

# gnu global with pygments (and universal-ctags), https://www.gnu.org/software/global/, http://pygments.org/
# https://github.com/universal-ctags/ctags
export GTAGSCONF=/usr/share/gtags/gtags.conf
export GTAGSLABEL=pygments

export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local/share

# https://wiki.archlinux.org/index.php/XDG_Base_Directory
export HISTFILE="$XDG_CACHE_HOME"/bash/bash_history
export LESSHISTFILE="$XDG_CACHE_HOME"/less/lesshst

[[ -f "$XDG_CONFIG_HOME"/bash/bash_aliases ]] && . "$XDG_CONFIG_HOME"/bash/bash_aliases
