# i keep using nano mistakenly
alias nano='vim'

# common
alias ll='ls -l --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ..='cd ..'
alias go_temp='cd $(mktemp -d)'
alias sc='systemctl'

# lgrep - less'd grep
GREP='/usr/bin/rg'
lgrep () {
  command $GREP $@ --color=always | less -R
}

# https://github.com/haikarainen/light
l () {
  if [ -z "$1" ]; then
    command light -G;
  else
    command light -S "$1";
  fi
}
